project:
  type: website

website:
  title: "SOEP study"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - results.qmd
      - appendix.qmd
    right:
      - text: "GitHub"
        href: "https://github.com/jackmo375/socio-economic-panel.git"
        icon: github

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



