---
title: "Appendix"
format:
  html:
    code-fold: true
execute: 
  echo: true
---

Import packages
```{r}
suppressWarnings(library(tidyverse))
suppressWarnings(library(cowplot))
suppressWarnings(library(knitr))
suppressWarnings(library(performance))
suppressWarnings(library(missForest))
```

# Summary statistics
```{r}
readRDS('../data/processed/data_clean.RDS') %>% as_tibble() -> data_clean
```

# Univariate summaries of the data

```{r}
#| label: tbl-persons-in-household
#| tbl-cap: Number of persons in the household

data_clean %>% group_by(study_year) %>% summarize(Q_0 = fivenum(persons_in_household)[1], Q_1 = fivenum(persons_in_household)[2], Q_2 = fivenum(persons_in_household)[3], Q_3 = fivenum(persons_in_household)[4], Q_4 = fivenum(persons_in_household)[5]) %>% kable()
```

```{r}
#| label: tbl-children-in-household
#| tbl-cap: number of children in the household

data_clean %>% group_by(study_year) %>% summarize(Q_0 = fivenum(children_in_household)[1], Q_1 = fivenum(children_in_household)[2], Q_2 = fivenum(children_in_household)[3], Q_3 = fivenum(children_in_household)[4], Q_4 = fivenum(children_in_household)[5]) %>% kable()
```

```{r}
#| label: tbl-years-of-education
#| tbl-cap: number of years of education

data_clean %>% group_by(study_year) %>% summarize(Q_0 = fivenum(number_of_years_of_education)[1], Q_1 = fivenum(number_of_years_of_education)[2], Q_2 = fivenum(number_of_years_of_education)[3], Q_3 = fivenum(number_of_years_of_education)[4], Q_4 = fivenum(number_of_years_of_education)[5]) %>% kable()
```

```{r}
#| label: tbl-ptotal-annual-income
#| tbl-cap: total annual income in euros

data_clean %>% group_by(study_year) %>% summarize(Q_0 = fivenum(total_annual_income)[1], Q_1 = fivenum(total_annual_income)[2], Q_2 = fivenum(total_annual_income)[3], Q_3 = fivenum(total_annual_income)[4], Q_4 = fivenum(total_annual_income)[5]) %>% kable()
```

```{r}
#| label: tbl-general-health-status
#| tbl-cap: general health status

data_clean %>% group_by(study_year) %>% summarize(Q_0 = fivenum(general_health_status)[1], Q_1 = fivenum(general_health_status)[2], Q_2 = fivenum(general_health_status)[3], Q_3 = fivenum(general_health_status)[4], Q_4 = fivenum(general_health_status)[5]) %>% kable()
```

```{r}
#| label: tbl-life-satisfaction
#| tbl-cap: life satisfaction

data_clean %>% group_by(study_year) %>% summarize(Q_0 = fivenum(life_satisfaction)[1], Q_1 = fivenum(life_satisfaction)[2], Q_2 = fivenum(life_satisfaction)[3], Q_3 = fivenum(life_satisfaction)[4], Q_4 = fivenum(life_satisfaction)[5]) %>% kable()
```

# Imputation results

```{r}
data_clean %>% summarise(across(everything(), ~ sum(is.na(.)))) %>%
  pivot_longer(cols = everything(),
               names_to = "variable",
               values_to = "n_missing") %>%
  mutate(percent_missing = round(n_missing * 100 / nrow(data_clean),1)) %>%
  kable()
```

```{r}
readRDS('../data/processed/impute_output.RDS') -> imp
```

```{r}
plot(imp$OOBerror, type = "b", pch = 19,
     xlab = "Iteration",
     ylab = "OOB error",
     main = "MissForest convergence")
```

# Model diagnostics

```{r}
readRDS('../results/lme_fit.RDS') -> lme_fit
```

```{r}
lme_fit %>% summary()
```
As can be seen in the above table, the scaled residuals are approximately normally distributed, with a slight left skew. The model `R^2` values are given below:
```{r}
performance::r2(lme_fit)
```

```{r}
plot(lme_fit)
```