---
title: "Model diagnostic report"
format:
  html:
    code-fold: true
execute: 
  echo: true
---
Import packages
```{r}
library(tidyverse)
library(lme4)
library(effects)
library(performance)
library(cowplot)
library(lattice)
```
```{r}
readRDS('../data/processed/data_imputed.RDS') -> data_imputed
readRDS('../results/lme_fit.RDS') -> lme_fit
read.csv('../data/raw/soep_practice_studv.csv') %>%
	as_tibble() -> data_raw
```

```{r}
lme_fit %>% summary()
```

```{r}
plot(lme_fit)
```

```{r}
qqnorm(resid(lme_fit))
qqline(resid(lme_fit))
```

```{r}
ranef(lme_fit) %>% as.data.frame %>% ggplot(aes(x=condval)) + geom_histogram() + theme_cowplot()
dotplot(ranef(lme_fit, condVar = TRUE))
```
```{r}
performance::r2(lme_fit)
```
Marginal R-squared: proportion of variance explained by the fixed effects only.
Conditional R-squared: proportion of variance explained by both fixed + random effects together.
So, since marginal is so much lower, this means the random effects are doing a lot of the explanatory work here. This means we could not do a straight regression model. 